plugins {
	id 'net.neoforged.moddev' version '2.0.+'
	id 'maven-publish'
	id "me.modmuss50.mod-publish-plugin" version "0.4.4"
	id 'me.fallenbreath.yamlang' version '1.4.1'
}

version = "${project.mod_version}+${property("deps.minecraft")}"
group = project.maven_group

base {
	archivesName = project.mod_id
}

neoForge {
	// Specify the version of NeoForge to use.
	version = property("deps.neoforge")

	parchment {
		mappingsVersion = "2024.11.17"
		minecraftVersion = property("deps.minecraft")
	}

	runs {
		client {
			client()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			logLevel = org.slf4j.event.Level.DEBUG
			systemProperty 'terminal.jline', 'true'
			systemProperty 'mixin.debug.export', 'true'
			systemProperty 'mixin.debug.verbose', 'true'
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

processResources {
	def properties = [
			version: project.version, mod_id: project.mod_id,
			github: project.mod_github, modrinth: project.mod_modrinth,
			minecraft_version_range: "[${minecraft_min},${minecraft_max}]"
	]

	inputs.properties properties

	filesMatching("META-INF/neoforge.mods.toml") {
		expand properties
	}
}

java {
	withSourcesJar()
	toolchain.languageVersion = JavaLanguageVersion.of(21)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.mod_id}"}
	}
}

yamlang {
	targetSourceSets = [sourceSets.main]
	inputDir = "assets/blahaj_totem/lang"
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

publishMods {
	file = jar.archiveFile
	additionalFiles.from sourcesJar.archiveFile
	displayName = "${property('mod_version')} for ${property('deps.minecraft')}"
	version = project.version
	changelog = rootProject.file("CHANGELOG.md").text
	type = STABLE
	modLoaders.add("neoforge")

	def min = property('minecraft_min')
	def max = property('minecraft_max')

	if (providers.gradleProperty('enjaraiModrinthToken').present) {
		modrinth {
			projectId = property('mod_modrinth')
			accessToken = providers.gradleProperty('enjaraiModrinthToken').get()

			if (min == max) {
				minecraftVersions.add(min)
			} else {
				minecraftVersionRange {
					start = min
					end = max
				}
			}
		}
	}

	if (providers.gradleProperty('enjaraiGithubToken').present) {
		github {
			repository = property('mod_github')
			accessToken = providers.gradleProperty('enjaraiGithubToken').get()

			commitish = property('git_branch')
			tagName = project.version
		}
	}
}